/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'clothing' : null } |
  { 'craftsHandmade' : null } |
  { 'other' : null } |
  { 'foodProduce' : null } |
  { 'furniture' : null } |
  { 'toolsEquipment' : null } |
  { 'services' : null } |
  { 'electronics' : null };
export interface Listing {
  'id' : ListingId,
  'title' : string,
  'contact' : string,
  'ownerId' : Principal,
  'createdAt' : Timestamp,
  'description' : string,
  'sellerName' : string,
  'imageUrl' : [] | [string],
  'category' : Category,
  'price' : Price,
}
export type ListingId = bigint;
export interface NewListingInput {
  'title' : string,
  'contact' : string,
  'description' : string,
  'sellerName' : string,
  'imageUrl' : [] | [string],
  'category' : Category,
  'price' : Price,
}
export type Price = bigint;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countListingsByCategory' : ActorMethod<[], Array<[Category, bigint]>>,
  'createListing' : ActorMethod<[NewListingInput], ListingId>,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'filterListingsByCategory' : ActorMethod<[Category], Array<Listing>>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingById' : ActorMethod<[ListingId], Listing>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<[string], Array<Listing>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];