/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'craftsHandmade' : IDL.Null,
  'other' : IDL.Null,
  'foodProduce' : IDL.Null,
  'furniture' : IDL.Null,
  'toolsEquipment' : IDL.Null,
  'services' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Price = IDL.Nat;
export const NewListingInput = IDL.Record({
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : Price,
});
export const ListingId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'ownerId' : IDL.Principal,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : Category,
  'price' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countListingsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
      ['query'],
    ),
  'createListing' : IDL.Func([NewListingInput], [ListingId], []),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'filterListingsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingById' : IDL.Func([ListingId], [Listing], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'craftsHandmade' : IDL.Null,
    'other' : IDL.Null,
    'foodProduce' : IDL.Null,
    'furniture' : IDL.Null,
    'toolsEquipment' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Price = IDL.Nat;
  const NewListingInput = IDL.Record({
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : Price,
  });
  const ListingId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'ownerId' : IDL.Principal,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : Category,
    'price' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countListingsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
        ['query'],
      ),
    'createListing' : IDL.Func([NewListingInput], [ListingId], []),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'filterListingsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingById' : IDL.Func([ListingId], [Listing], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func([IDL.Text], [IDL.Vec(Listing)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };