/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Price = bigint;
export type Timestamp = bigint;
export type ListingId = bigint;
export interface Listing {
    id: ListingId;
    title: string;
    contact: string;
    ownerId: Principal;
    createdAt: Timestamp;
    description: string;
    sellerName: string;
    imageUrl?: string;
    category: Category;
    price: Price;
}
export interface NewListingInput {
    title: string;
    contact: string;
    description: string;
    sellerName: string;
    imageUrl?: string;
    category: Category;
    price: Price;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    clothing = "clothing",
    craftsHandmade = "craftsHandmade",
    other = "other",
    foodProduce = "foodProduce",
    furniture = "furniture",
    toolsEquipment = "toolsEquipment",
    services = "services",
    electronics = "electronics"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    countListingsByCategory(): Promise<Array<[Category, bigint]>>;
    createListing(input: NewListingInput): Promise<ListingId>;
    deleteListing(id: ListingId): Promise<void>;
    filterListingsByCategory(category: Category): Promise<Array<Listing>>;
    getAllListings(): Promise<Array<Listing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListingById(id: ListingId): Promise<Listing>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(keyword: string): Promise<Array<Listing>>;
}
import type { Category as _Category, Listing as _Listing, ListingId as _ListingId, NewListingInput as _NewListingInput, Price as _Price, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async countListingsByCategory(): Promise<Array<[Category, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.countListingsByCategory();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countListingsByCategory();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: NewListingInput): Promise<ListingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_NewListingInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_NewListingInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteListing(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterListingsByCategory(arg0: Category): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByCategory(to_candid_Category_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByCategory(to_candid_Category_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingById(arg0: ListingId): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_Listing_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_Listing_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListings(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    title: string;
    contact: string;
    ownerId: Principal;
    createdAt: _Timestamp;
    description: string;
    sellerName: string;
    imageUrl: [] | [string];
    category: _Category;
    price: _Price;
}): {
    id: ListingId;
    title: string;
    contact: string;
    ownerId: Principal;
    createdAt: Timestamp;
    description: string;
    sellerName: string;
    imageUrl?: string;
    category: Category;
    price: Price;
} {
    return {
        id: value.id,
        title: value.title,
        contact: value.contact,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        description: value.description,
        sellerName: value.sellerName,
        imageUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.imageUrl)),
        category: from_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Category, bigint]): [Category, bigint] {
    return [
        from_candid_Category_n5(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    craftsHandmade: null;
} | {
    other: null;
} | {
    foodProduce: null;
} | {
    furniture: null;
} | {
    toolsEquipment: null;
} | {
    services: null;
} | {
    electronics: null;
}): Category {
    return "clothing" in value ? Category.clothing : "craftsHandmade" in value ? Category.craftsHandmade : "other" in value ? Category.other : "foodProduce" in value ? Category.foodProduce : "furniture" in value ? Category.furniture : "toolsEquipment" in value ? Category.toolsEquipment : "services" in value ? Category.services : "electronics" in value ? Category.electronics : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Category, bigint]>): Array<[Category, bigint]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_NewListingInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewListingInput): _NewListingInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contact: string;
    description: string;
    sellerName: string;
    imageUrl?: string;
    category: Category;
    price: Price;
}): {
    title: string;
    contact: string;
    description: string;
    sellerName: string;
    imageUrl: [] | [string];
    category: _Category;
    price: _Price;
} {
    return {
        title: value.title,
        contact: value.contact,
        description: value.description,
        sellerName: value.sellerName,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: to_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    clothing: null;
} | {
    craftsHandmade: null;
} | {
    other: null;
} | {
    foodProduce: null;
} | {
    furniture: null;
} | {
    toolsEquipment: null;
} | {
    services: null;
} | {
    electronics: null;
} {
    return value == Category.clothing ? {
        clothing: null
    } : value == Category.craftsHandmade ? {
        craftsHandmade: null
    } : value == Category.other ? {
        other: null
    } : value == Category.foodProduce ? {
        foodProduce: null
    } : value == Category.furniture ? {
        furniture: null
    } : value == Category.toolsEquipment ? {
        toolsEquipment: null
    } : value == Category.services ? {
        services: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
